module.exports = {
    queryString: [
        '100daysofcode',
        '301daysofcode',
        'freecodecamp',
        'github',
        'github best practices',
        'vscode',
        'vscode best practices',
        'visual studio code',
        'visual studio code  best practices',
        'atomio',
        'atom.io',
        'nodejs',
        'nodejs best practices',
        'node.js',
        'node.js best practices',
        'npmjs',
        'npmjs best practices',
        'npm.js',
        'npm.js best practices',
        'vuejs',
        'vuejs best practices',
        'vue.js',
        'vue.js best practices',
        'inferno_js',
        'inferno_js best practices',
        'infernojs',
        'infernojs best practices',
        'inferno.js',
        'inferno.js best practices',
        'laravel',
        'laravel best practices',
        'laravelphp',
        'laravelphp best practices',
        'conditioner.js',
        'conditionerjs',
        'svelte.js',
        'sveltejs',
        'docker',
        'docker best practices'
    ],
    resultType: [
        'mixed',
        'recent',
        'popular'
    ],
    responseString: [
        'Hi @screenName thanks for the follow! !CR',
        '@screenName thanks for following! !CR',
        'Hey @screenName thanks for the follow! !CR',
        'Thanks for following @screenName! !CR',
        'Hey @screenName, thanks for following! !CR',
        'Awesome @screenName, thanks for following! !CR',
        'Thanks for the follow @screenName! !CR',
        'Thanks for following @screenName! How are you today? !CR'
    ]
};
